baseURL: 'https://www.ehri.at/'
languageCode: de-AT
title: Austria
theme: ehri-nn
copyright: '© 2010-{year} EHRI Consortium.'
defaultContentLanguage: en
dateFormat: '2 January 2006'
summaryLength: 40
params:
  titleShort: EHRI-AT
  facebookUrl: 'https://facebook.com/EHRIproject'
  twitterUrl: 'https://twitter.com/EHRIproject'

  # `contactName` and `contactEmail` are used to populate the contact page.
  contactName: EHRI-AT
  contactEmail: info@ehri.at

  # `contactForm` is a boolean that determines whether the contact form should be shown.
  contactForm: false

  # `contactFormUrl` is the POST action of the form that will be used to send the contact email.
  contactFormUrl: dummy

  # `funders` is a list of funding bodies, each with a name, logo and an optional URL.
  # If the URL is not provided, the logo will not be linked. The logo should be in the
  # `static/images` folder.
  funders:
    - name: EHRI is funded by the European Commission
      logo: 'eu-logo.svg'
      url: 'https://ec.europa.eu/info/departments/research-and-innovation_en'
    - name: Bundesministerium für Bildung, Wissenschaft und Forschung
      logo: 'bmbwf_logo.png'
      url: 'https://www.bmbwf.gv.at/'


# Configure syntax highlighting for the examples on the `training` page
markup:
  highlight:
    style: xcode

# Configure taxonomy terms
taxonomies:
  - name: category
    weight: 1
  - name: tag
    weight: 2

# Menu configuration. Labels are in the i18n folders:
menu:
  main:
    - identifier: news
      pageRef: news
      weight: 10
    - identifier: about
      pageRef: about
      weight: 20
    - identifier: partners
      pageRef: partners
      weight: 30
    - identifier: projects
      pageRef: projects
      weight: 40
    - identifier: services
      pageRef: services
      weight: 50
    - identifier: contact
      pageRef: contact
      weight: 60
  footer:
    - identifier: about
      pageRef: about
      weight: 20
    - identifier: partners
      pageRef: partners
      weight: 30
    - identifier: projects
      pageRef: projects
      weight: 40
  services:
    - identifier: portal
      pageRef: 'https://portal.ehri-project.eu/'
      weight: 10
    - identifier: document_blog
      pageRef: 'https://blog.ehri-project.eu/'
      weight: 20
    - identifier: digital_tools_guide
      pageRef: 'https://github.com/EHRI/ehri-data-analysis-tools'
      weight: 30
    - identifier: podcast
      pageRef: 'https://www.ehri-project.eu/ehri-podcast-for-the-living-and-the-dead'
      weight: 40


# Language overrides for menu config. TODO: figure out
# how not to duplicate things in e.g. the services menu
languages:
  en:
    title: Austria
    weight: 1
  de:
    title: Österreich
    weight: 2
    menu:
      main:
        - identifier: news
          pageRef: de/news/
          weight: 10
        - identifier: about
          pageRef: de/about/
          weight: 20
        - identifier: partners
          pageRef: de/partners
          weight: 30
        - identifier: projects
          pageRef: de/projects
          weight: 40
        - identifier: services
          pageRef: de/services
          weight: 50
        - identifier: contact
          pageRef: de/contact
          weight: 60
      footer:
        - identifier: about
          pageRef: de/about/
          weight: 20
        - identifier: partners
          pageRef: de/partners
          weight: 30
        - identifier: projects
          pageRef: de/projects
          weight: 40
      services:
        - identifier: document_blog
          pageRef: 'https://blog.ehri-project.eu/'
          weight: 20
        - identifier: digital_tools_guide
          pageRef: 'https://github.com/EHRI/ehri-data-analysis-tools'
          weight: 30
        - identifier: podcast
          pageRef: 'https://www.ehri-project.eu/ehri-podcast-for-the-living-and-the-dead'
          weight: 40
