baseURL = 'http://example.org/'
languageCode = 'en-gb'
title = 'United Kingdom'
theme = 'ehri-nn'
copyright = "© 2010-{year} EHRI Consortium."

defaultContentLanguage = 'en'

[params]
    titleShort = 'EHRI-UK'
    facebook_url = 'https://facebook.com/EHRIproject'
    twitter_url = 'https://twitter.com/EHRIproject'

    contact_name = 'EHRI UK'
    contact_email = 'feedback@ehri-uk.org'

[languages]
  [languages.en]
    title = 'United Kingdom'
    weight = 1
  [languages.cy]
    title = 'Deyrnas Unedig'
    weight = 2
    [languages.cy.menu]
      [[languages.cy.menu.main]]
        name = 'Am'
        pageRef = 'cy/about/'
        weight = 20
      [[languages.cy.menu.main]]
        name = 'Partneriaid'
        pageRef = 'cy/partners'
        weight = 30
      [[languages.cy.menu.main]]
        name = 'Cymrodoriaethau a Hyfforddiant'
        pageRef = 'cy/training'
        weight = 40
      [[languages.cy.menu.main]]
        name = 'Gwasanaethau'
        pageRef = 'cy/services'
        weight = 50
      [[languages.cy.menu.main]]
        name = 'Cysylltwch'
        pageRef = 'cy/contact'
        weight = 60



# Main menu
[menu]
[[menu.main]]
  name = 'About'
  pageRef = 'about'
  weight = 20
[[menu.main]]
  name = 'Partners'
  pageRef = 'partners'
  weight = 30
[[menu.main]]
  name = 'Fellowships & Training'
  pageRef = 'training'
  weight = 40
[[menu.main]]
  name = 'Services'
  pageRef = 'services'
  weight = 50
[[menu.main]]
  name = 'Contact'
  pageRef = 'contact'
  weight = 60

# Footer page menu
[[menu.footer]]
  name = 'About'
  pageRef = 'about'
  weight = 20
[[menu.footer]]
  name = 'Partners'
  pageRef = 'partners'
  weight = 30
[[menu.footer]]
  name = 'Fellowships & Training'
  pageRef = 'training'
  weight = 40
    [[languages.cy.menu.footer]]
      name = 'Am'
      pageRef = 'cy/about/'
      weight = 20
    [[languages.cy.menu.footer]]
      name = 'Partneriaid'
      pageRef = 'cy/partners'
      weight = 30
    [[languages.cy.menu.footer]]
      name = 'Cymrodoriaethau a Hyfforddiant'
      pageRef = 'cy/training'
      weight = 40

# Services lists
[[menu.services]]
  name = 'Portal'
  pageRef = 'https://portal.ehri-project.eu/'
  weight = 10
[[menu.services]]
  name = 'Document Blog'
  pageRef = 'https://blog.ehri-project.eu/'
  weight = 20
[[menu.services]]
  name = 'Digital Tools Guide'
  pageRef = 'https://github.com/EHRI/ehri-data-analysis-tools'
  weight = 30
[[menu.services]]
  name = 'Podcast'
  pageRef = 'https://www.ehri-project.eu/ehri-podcast-for-the-living-and-the-dead'
  weight = 40
    [[languages.cy.menu.services]]
      name = 'Document Blog'
      pageRef = 'https://blog.ehri-project.eu/'
      weight = 20
    [[languages.cy.menu.services]]
      name = 'Digital Tools Guide'
      pageRef = 'https://github.com/EHRI/ehri-data-analysis-tools'
      weight = 30
    [[languages.cy.menu.services]]
      name = 'Podcast'
      pageRef = 'https://www.ehri-project.eu/ehri-podcast-for-the-living-and-the-dead'
      weight = 40
